---
- name: "Install mysql server"
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - mariadb
      - mariadb-server
- yum:
    name: MySQL-python
    state: present
- service:
    name: mariadb
    state: restarted
- mysql_db:
    name: "{{database_name}}"
    state: present
- mysql_user:
    name: bob
    password: 12345
    priv: '*.*:ALL'
    state: present
    host: '%'