---
     - name: "install the latest version of Apache srv"
       yum:
         name: httpd
         state: latest
       become: yes
     - name: "PHP"
       yum:
         name: "{{packages}}"
         state: latest
       vars:
         packages:
            - php
            - php-mysql

