---
     - name: "install the latest version of Apache srv"
       yum:
         name: httpd
         state: latest
       become: yes
     - name: "PHP"
       yum:
         name: "{{packages}}"
         state: latest
       vars:
         packages:
            - php
<<<<<<< HEAD
            - MySQL-python
            - php-mysql
             
=======
            - php-mysql
>>>>>>> refs/remotes/origin/master

