---
     - name: "download wordpress"
       get_url:
          url: https://wordpress.org/latest.zip
          dest: /tmp/wordpress.zip
     - name: "unarchive wordpress"
       unarchive:
          src: /tmp/wordpress.zip
          dest: /var/www
          remote_src: yes
     - name: "put apache conf"
       template: 
           src: templates/vhost.conf
           dest: /etc/httpd/conf.d/vhost.conf
     - name: "start http service"
       service:
         name: httpd
         state: restarted     
     - name: "put wp_config"
       copy:
           src: templates/wp-config.php
           dest: "{{wp_install_directory}}/wp-config.php"
     - name: Update WordPress config file
       lineinfile:
           dest="{{wp_install_directory}}/wp-config.php"
           regexp="{{ item.regexp }}"
           line="{{ item.line }}"
       with_items:
           - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{db_name}}');"}
           - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{db_pwd}}');"}
           - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{db_user}}');"}        
           - {'regexp': "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_HOST', '{{db_ip}}');"}    

